### ISSUE TITLE
Extra information present in the DWARF data that dwarf2cpp does not currently handle

### ISSUE THREAD

**Issue by DaZombieKiller** [Ralakimus/Sonic-CD-Gems-PS2-dwarf2cpp-Dumps#1]
Crazy coincidence, but I was just looking into DWARF 1.x debugging data today (for PS2 games in particular), and came across [your thread on sonicretro](https://forums.sonicretro.org/index.php?threads/sonic-cd-gems-collection-linker-disassembly-dumps.41026/) after googling some random strings. I would have posted this there, but it seems a new account isn't allowed to post in the thread.

It seems that Sonic CD Gems was compiled with the MetroWerkz compiler just like the PS2 games I'm looking into. That compiler adds extensions to the DWARF 1.x format, so dwarf2cpp doesn't currently take full advantage of all the information available. Luckily, I just finished figuring these extensions out (the linker has all of the information intact for debug output):
```c
// tags
TAG_MW_overlay_branch = 0x4080,

// attributes
AT_MW_mangled            = 0x2000 | FORM_STRING,
AT_MW_restore_SP         = 0x2010 | FORM_BLOCK2,
AT_MW_global_ref         = 0x2020 | FORM_REF,
AT_MW_global_ref_by_name = 0x2030 | FORM_STRING,
AT_MW_restore_S0         = 0x2040 | FORM_BLOCK2,
AT_MW_restore_S1         = 0x2050 | FORM_BLOCK2,
AT_MW_restore_S2         = 0x2060 | FORM_BLOCK2,
AT_MW_restore_S3         = 0x2070 | FORM_BLOCK2,
AT_MW_restore_S4         = 0x2080 | FORM_BLOCK2,
AT_MW_restore_S5         = 0x2090 | FORM_BLOCK2,
AT_MW_restore_S6         = 0x20A0 | FORM_BLOCK2,
AT_MW_restore_S7         = 0x20B0 | FORM_BLOCK2,
AT_MW_restore_S8         = 0x20C0 | FORM_BLOCK2,
AT_MW_restore_F20        = 0x20D0 | FORM_BLOCK2,
AT_MW_restore_F21        = 0x20E0 | FORM_BLOCK2,
AT_MW_restore_F22        = 0x20F0 | FORM_BLOCK2,
AT_MW_restore_F23        = 0x2100 | FORM_BLOCK2,
AT_MW_restore_F24        = 0x2110 | FORM_BLOCK2,
AT_MW_restore_F25        = 0x2120 | FORM_BLOCK2,
AT_MW_restore_F26        = 0x2130 | FORM_BLOCK2,
AT_MW_restore_F27        = 0x2140 | FORM_BLOCK2,
AT_MW_restore_F28        = 0x2150 | FORM_BLOCK2,
AT_MW_restore_F29        = 0x2160 | FORM_BLOCK2,
AT_MW_restore_F30        = 0x2170 | FORM_BLOCK2,
AT_MW_restore_D20        = 0x2180 | FORM_BLOCK2,
AT_MW_restore_D21        = 0x2190 | FORM_BLOCK2,
AT_MW_restore_D22        = 0x21A0 | FORM_BLOCK2,
AT_MW_restore_D23        = 0x21B0 | FORM_BLOCK2,
AT_MW_restore_D24        = 0x21C0 | FORM_BLOCK2,
AT_MW_restore_D25        = 0x21D0 | FORM_BLOCK2,
AT_MW_restore_D26        = 0x2240 | FORM_BLOCK2,
AT_MW_restore_D27        = 0x2250 | FORM_BLOCK2,
AT_MW_restore_D28        = 0x2260 | FORM_BLOCK2,
AT_MW_restore_D29        = 0x2270 | FORM_BLOCK2,
AT_MW_restore_D30        = 0x2280 | FORM_BLOCK2,
AT_MW_overlay_id         = 0x2290 | FORM_DATA4,
AT_MW_overlay_name       = 0x22A0 | FORM_STRING,
AT_MW_global_refs_block  = 0x2300 | FORM_BLOCK2,
AT_MW_local_spoffset     = 0x2310 | FORM_BLOCK4,
AT_MW_MIPS16             = 0x2330 | FORM_STRING,
AT_MW_DWARF2_location    = 0x2340 | FORM_BLOCK2,

// fundamental types
FT_MW_long_long          = 0x18,
FT_MW_signed_long_long   = 0x19,
FT_MW_unsigned_long_long = 0x1A,
FT_MW_fixed_vector_8x8   = 0xA408,
FT_MW_int128             = 0xA510,
FT_MW_signed_int_16x8    = 0xA610,
FT_MW_signed_int_8x16    = 0xA710,
FT_MW_signed_int_4x32    = 0xA810,
FT_MW_unsigned_int_16x8  = 0xA910,
FT_MW_unsigned_int_8x16  = 0xAA10,
FT_MW_unsigned_int_4x32  = 0xAB10,
FT_MW_vec2x32float       = 0xAC00,

// locations
OP_MW_FPREG  = 0x80,
OP_MW_FPDREG = 0x81,
OP_MW_DREF8  = 0x82,
```
I haven't looked into extending dwarf2cpp to handle these since I'm working on my own tool that contains much of the same functionality, but I hope this information comes in handy if you want to take a stab at it yourself.

**Comment by DaZombieKiller** [comment]
It's likely also worth paging @seilweiss on this, since dwarf2cpp does currently handle one MetroWerkz extension: `AT_mangled` (just under a different name, so I assume it was implemented with guesswork). I presume the original target game (Battle for Bikini Bottom) was also built with the MetroWerkz compiler and therefore it too would contain the extra information.

**Comment by DevsArchive** [comment]
While it's cool that you bring this up, in this case, those extensions don't appear to be used in Sonic CD. All those "restore" attributes are probably just tags indicating CPU registers that get saved and restored in a function. The "mangled" one sounds like that's more for C++, while Sonic CD in this case was ported to C. Sonic CD also defines its own fixed point unions/structures, which makes sense, as it's just a port of the 1996 PC version, which did not use this compiler, obviously. Also didn't seem to use 64-bit types. Have no idea about the rest of them, but I reckon that for this, it's just not going to be of any use.

**Comment by DaZombieKiller** [comment]
> All those "restore" attributes are probably just tags indicating CPU registers that get saved and restored in a function.

That does appear to be their purpose, yeah.

> The "mangled" one sounds like that's more for C++

Yep, it's just the mangled symbol name for C++ functions.

> Have no idea about the rest of them, but I reckon that for this, it's just not going to be of any use.

Makes sense, I didn't personally verify how much of it was used in Sonic CD -- I just noticed that some of the MW attributes were present in the `ld` output you posted, and figured I might as well point this out just in case.

**Comment by DevsArchive** [comment]
Could you specify which MW attributes were used exactly?

**Comment by DaZombieKiller** [comment]
`AT_global_refs_block`, `AT_restore_SP`, `AT_restore_S0` and `AT_restore_S1` all appear in the snippet posted [here](https://forums.sonicretro.org/index.php?threads/sonic-cd-gems-collection-linker-disassembly-dumps.41026/#post-1021695).

**Comment by DevsArchive** [comment]
Yeah, those "restore" ones are exactly what I thought. Looking at a disassembly shows matches between the registers specified in the attributes and the registers that are saved and restored at the start and end of functions. "AT_global_refs_block", appears to be references to global variables from within the code, represented as a raw byte array. Those references can be seen by disassembling/decompiling the code, which is a bit outside the scope of this repository, but I guess it would be nice to have some kind of comment added inside the functions to show those references, though.

I'm gonna go ahead and close this, but you should definitely bring this up with seilweiss.
